### PR TITLE
bootstrap with knative-sandbox/hack

### PR DESCRIPTION
**Pull request by maximilien**

### CODE REVIEW

**Comment by maximilien** [comment]
@rhuss or @navidshaikh please LGTM when you have a minute. Still bootstrapping... Thx

**Review by navidshaikh — COMMENTED** [review]
@maximilien : can you resync with latest in knative/hack repo? also is that all required for test-infra setup? IIRC we'd need to have some prow jobs at https://github.com/knative/test-infra as well? cc: @evankanderson

**Comment by maximilien** [comment]
Thanks @navidshaikh I will refresh

**Review by rhuss — COMMENTED** [review]
This is not how the scripts in from knative/hack should be picked up. Instead, you should add a `hack/tools.go` with an anonymous import to the the hack repo (like in the client) and then run `go mod vendor`. I added an issue over there https://github.com/knative/hack/issues/35 to add this to the README of the hack repo, as I don't think this is documented anywhere.

**Comment by maximilien** [comment]
Closing this. See issue #2

**Pull request closed without merging**
